import streamlit as st
from pathlib import Path

st.set_page_config(
    page_title="Fraud Investigator | AI-Powered FinTech",
    page_icon="🛡️",
    layout="wide"
)

# Sidebar Info
st.sidebar.title("App Navigation")
st.sidebar.info("""
Use the sidebar to navigate between:
1. **Analytics**: Market trends.
2. **Predictor**: Individual checks.
3. **Metrics**: Model health.
4. **Info**: How it works.
""")

# Main Content
st.title("🛡️ AI-Powered Digital Wallet Fraud Investigator")
st.markdown("---")

col1, col2 = st.columns([2, 1])

with col1:
    st.markdown("""
    ### Welcome to the Fraud Investigator Dashboard
    This platform provides real-time fraud detection and automated investigation reporting for Pakistani Digital Wallets (e.g., EasyPaisa, JazzCash).
    
    #### 🚀 Key Features:
    - **Real-time Scoring**: Instant ML-based fraud probability.
    - **AI Investigation**: Narrative reports generated by Llama 3 for flagged transactions.
    - **Advanced Analytics**: Visual insights into fraud patterns across cities and timeframes.
    
    #### 🛠️ How to Get Started:
    1. Go to **Analytics** to see overall trends.
    2. Use the **Predictor** to test specific transaction scenarios.
    3. Check **Model Metrics** for technical performance details.
    4. Visit the **Info** page for a deep dive into the technology.
    """)

with col2:
    # Robust image path lookup
    root = Path(__file__).resolve().parent.parent.parent
    img_options = [
        root / "fraud.png",
        root / "src" / "hacker.png",
    ]
    
    img_path = None
    for p in img_options:
        if p.exists():
            img_path = p
            break
            
    if img_path:
        st.image(str(img_path), width=200)
    else:
        st.image("https://img.icons8.com/clouds/256/000000/security-shield.png", width=200)
    st.success("System Status: **Active**")
    st.info("Model Version: **v1.0.2 (XGBoost)**")

st.markdown("---")
st.caption("Developed for the Agentic Hackathon | 2026")
