import streamlit as st
from pathlib import Path
import sys

# Add src/app to path for utils imports
sys.path.append(str(Path(__file__).parent))
from utils.sidebar_nav import show_sidebar

# Load Custom CSS
def local_css(file_name):
    with open(file_name) as f:
        st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)

st.set_page_config(
    page_title="Fraud Investigator | AI-Powered FinTech",
    page_icon="🛡️",
    layout="wide"
)

# Apply CSS
css_path = Path(__file__).parent / "style.css"
if css_path.exists():
    local_css(str(css_path))

# Sidebar Info
show_sidebar()

# Main Content
st.title("🛡️ AI-Powered Digital Wallet & Fraud Investigator")
st.markdown("##### Real-time fraud detection and automated investigation for Pakistani Digital Wallets.")
st.markdown("---")

col1, col2 = st.columns([1.5, 1])

with col1:
    st.markdown("""
    ### 🚀 Mission Overview
    This platform leverages state-of-the-art Machine Learning (XGBoost) and Generative AI to safeguard digital transactions.
    
    <div class="custom-card">
        <h4>⚡ Real-time Scoring</h4>
        <p>Instant ML-based fraud probability for every transaction.</p>
    </div>
    <div class="custom-card" style="border-left-color: #4B9FFF;">
        <h4>🤖 AI Investigation</h4>
        <p>Narrative reports generated by AI for high-risk flagged transactions.</p>
    </div>
    <div class="custom-card" style="border-left-color: #4BFF9F;">
        <h4>📊 Advanced Analytics</h4>
        <p>Visual insights into fraud patterns across cities and timeframes.</p>
    </div>
    """, unsafe_allow_html=True)

with col2:
    # Robust image path lookup
    root = Path(__file__).resolve().parent.parent.parent
    img_options = [
        root / "src" / "hacker.png",
        root / "hacker.png",
    ]
    
    img_path = None
    for p in img_options:
        if p.exists():
            img_path = p
            break
            
    if img_path:
        st.image(str(img_path), use_column_width=True)
    else:
        st.image("https://img.icons8.com/clouds/512/000000/security-shield.png", width=300)
    
    st.markdown("---")
    c1, c2 = st.columns(2)
    c1.success("Status: **Active**")
    c2.info("v1.0.2 (XGBoost)")

st.markdown("---")
st.caption("Developed for the Agentic Hackathon | 2026 | Built with ❤️ using Streamlit")
